modLoader="javafml"
loaderVersion="[${minFMLVersion},)"
issueTrackerURL="${modIssueUrl}"
license="${modLicense}"
logoFile="mod_logo.png"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
description="${modDescription}"
authors="${modAuthor}"
displayURL="${modPageUrl}"
updateJSONURL="${modUpdateUrl}"
displayTest="${modForgeDisplayTest}"

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${minForgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${minMinecraftVersion},${nextMinecraftVersion})"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId = "architectury"
mandatory = true
versionRange = "[${archVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "coolcat_lib"
mandatory = true
versionRange = "[${ccLibVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "ftbultimine"
mandatory = true
versionRange = "[${ftbUltimineVersion},)"
ordering = "NONE"
side = "BOTH"

[modproperties.${modId}]
catalogueImageIcon="mod_logo.png"
configuredBackground="${modId}:textures/gui/adv_background.png"