apply from: "https://raw.githubusercontent.com/ixDarkLorD/ModResources/main/gradle/v3/fabric.gradle"

loom {
    runs {
        devClient {
            client()
            setConfigName("Fabric Dev Client ${libs.versions.minecraft.get()}")
            programArgs "--username", "Dev"
        }
        server {
            runDir("../run/server")
        }
    }
}

dependencies {
    api libs.architectury.fabric
    api "net.ixdarklord.coolcatlib:coolcatlib-fabric:${libs.versions.minecraft.get()}-${coolcatlib_version}"
    api libs.forgeconfigapiport.fabric

    compileOnlyApi libs.jei.api.fabric
    runtimeOnly libs.jei.fabric
    compileOnly libs.trinkets
    // Trinkets injects interfaces into vanilla classes, so dev runs need it on the runtime classpath too.
    localRuntime libs.trinkets

    api "dev.ftb.mods:ftb-ultimine-fabric:${ftbultimine_version}"
    api "dev.ftb.mods:ftb-library-fabric:${ftblibrary_version}"
}
