plugins {
    alias libs.plugins.architectury.loom apply false
    alias libs.plugins.architectury.plugin apply false
    alias libs.plugins.shadow apply false
    alias libs.plugins.modpublisher apply false
}

allprojects {
    repositories {
        maven {
            url "https://maven.saps.dev/releases"
            content {
                includeGroup "dev.latvian.mods"
            }
        }
        maven {
            url "https://maven.saps.dev/snapshots"
            content {
                includeGroup "dev.latvian.mods"
            }
        }
        maven {
            url "https://maven.ftb.dev/releases"
            content {
                includeGroup "dev.ftb.mods"
            }
        }

        maven {
            url "https://maven.ftb.dev/snapshots"
            content {
                includeGroup "dev.ftb.mods"
            }
        }
    }
}

// shared_scripts_url points the shared scripts at another copy, e.g. a local ModResources checkout.
apply from: "${findProperty("shared_scripts_url") ?: "https://raw.githubusercontent.com/ixDarkLorD/ModResources/main/gradle/v4"}/main.gradle"
