name: Bug Report
description: Create a bug report to help us improve
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - ixDarkLorD
body:
  - type: markdown
    attributes:
      value: "**Thank you for introducing the issue! And keep helping us to keep improving. We appreciate your time!**"
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is.
        placeholder: "Example: I clicked the button, and the game stopped working!"
      validations:
        required: true
  -   type: textarea
      attributes:
        label: To Reproduce
        description: Tell us about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          4.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Catch the bug In Action!
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Crash Report or Log
        description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist.
        placeholder: "Please don't paste the whole crash report in this issue"
      validations:
        required: false
  -   type: input
      attributes:
        label: OS
        description: The operating system you were using when the bug occurred
        placeholder: "e.g. Windows 11, iOS"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occurred
        options:
          - "1.18.2"
          - "1.19.2"
          - "1.20.1"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: ModLoader
        description: What is the ModLoader you were using when the bug occurred
        options:
          - "Forge"
          - "Fabric"
      validations:
        required: true
  -   type: input
      attributes:
        label: Mod Version
        description: The mod version you where using when the bug occurred
      validations:
        required: true
